name: ${project.name}
version: ${project.version}
description: ${project.description}
main: net.justminecraft.prisons.PrisonsPlugin
author: PureGero
softdepend: [WorldEdit, PureNetwork]
commands:
  balance:
    description: Prisons balance command
    aliases: [bal, money, tokens, coins]
    permission: prisons.balance
  setupprisons:
    description: Set up prisons
    permission: prisons.setupprisons
  spawn:
    description: Prisons spawn command
    permission: prisons.spawn
  warp:
    description: Prisons warp command
    permission: prisons.warp
permissions:
  prisons.balance:
    default: true
  prisons.setupprisons:
    default: op
  prisons.spawn:
    default: true
  prisons.warp:
    default: true
