name: ${project.name}
version: ${project.version}
description: ${project.description}
main: net.justminecraft.prisons.PrisonsPlugin
author: PureGero
softdepend: [WorldEdit, PureNetwork]
commands:
  balance:
    description: Prisons balance command
    aliases: [bal, money, tokens, coins]
    permission: prisons.balance
  prestige:
    description: Prisons prestige command
    permission: prisons.prestige
  rankup:
    description: Prisons rankup command
    permission: prisons.rankup
  setupprisons:
    description: Set up prisons
    permission: prisons.setupprisons
  spawn:
    description: Prisons spawn command
    permission: prisons.spawn
  stopkeymessages:
    description: Prisons stopkeymessages command
    permission: prisons.stopkeymessages
  stopkeyusemessages:
    description: Prisons stopkeyusemessages command
    permission: prisons.stopkeyusemessages
  stoptokenmessages:
    description: Prisons stoptokenmessages command
    permission: prisons.stoptokenmessages
  warp:
    description: Prisons warp command
    permission: prisons.warp
  pay:
    description: Pay another player coins or tokens
    permission: prisons.balance
permissions:
  prisons.balance:
    default: true
  prisons.prestige:
    default: true
  prisons.rankup:
    default: true
  prisons.setupprisons:
    default: op
  prisons.spawn:
    default: true
  prisons.stopkeymessages:
    default: true
  prisons.stopkeyusemessages:
    default: true
  prisons.stoptokenmessages:
    default: true
  prisons.warp:
    default: true
